-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 15:04:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `PNome` VARCHAR(45) NOT NULL,
  `Nmeio` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL COMMENT 'Adcionar contraint de unicidade para (nome completo) \nunique (Nome, M, Sobrenome)',
  `Identificação_documento` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `PJ_idCliente` INT NOT NULL,
  `PF_idCliente` INT NOT NULL,
  `Dt_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idCliente`, `Dt_nascimento`, `PF_idCliente`, `PJ_idCliente`),
  UNIQUE INDEX `Identificação_documento_UNIQUE` (`Identificação_documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Status` ENUM('EM ANDAMENTO', 'PROCESSANDO', 'ENVIADO', 'ENTREGUE') NOT NULL DEFAULT 'PROCESSANDO',
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Entrega_idEntrega`, `Pagamento_idPagamento`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  INDEX `fk_Pedido_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsável`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Responsável` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Responsável` (
  `idResponsável` INT NOT NULL,
  `Nível_help_desk` INT NULL,
  `Nome` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsável`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_de_Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem_de_Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_de_Serviço` (
  `idOrdem_de_Serviço` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem_de_Serviço`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Ordem_de_Serviço_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_de_Serviço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Analise_de_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Analise_de_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Analise_de_pedido` (
  `Responsável_idResponsável` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Responsável_idResponsável`, `Pedido_idPedido`),
  INDEX `fk_Responsável_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Responsável_has_Pedido_Responsável1_idx` (`Responsável_idResponsável` ASC) VISIBLE,
  CONSTRAINT `fk_Responsável_has_Pedido_Responsável1`
    FOREIGN KEY (`Responsável_idResponsável`)
    REFERENCES `mydb`.`Responsável` (`idResponsável`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsável_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Campus` VARCHAR(45) NOT NULL,
  `idCoordenador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`, `idCoordenador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Departamento_idDepartamento1` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Departamento_idDepartamento`, `Departamento_idDepartamento1`),
  INDEX `fk_Professor_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  INDEX `fk_Professor_Departamento2_idx` (`Departamento_idDepartamento1` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Departamento2`
    FOREIGN KEY (`Departamento_idDepartamento1`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Professor_idProfessor`),
  INDEX `fk_Aluno_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Departamento_Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Departamento_idDepartamento`, `Departamento_Curso_idCurso`),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento_idDepartamento` ASC, `Departamento_Curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`, `Professor_idProfessor`),
  INDEX `fk_Disciplina_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matriculado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matriculado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Matriculado` (
  `Aluno_idAluno` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Disciplina_idDisciplina`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina & Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disciplina & Cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina & Cursos` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Curso_idCurso`),
  INDEX `fk_Disciplina_has_Curso_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Curso_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Curso_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pré-requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pré-requisitos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pré-requisitos` (
  `idPré-requisitos` INT NOT NULL,
  PRIMARY KEY (`idPré-requisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pré-requisitos das disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pré-requisitos das disciplinas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pré-requisitos das disciplinas` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Pré-requisitos_idPré-requisitos` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Pré-requisitos_idPré-requisitos`),
  INDEX `fk_Disciplina_has_Pré-requisitos_Pré-requisitos1_idx` (`Pré-requisitos_idPré-requisitos` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Pré-requisitos_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Pré-requisitos_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Pré-requisitos_Pré-requisitos1`
    FOREIGN KEY (`Pré-requisitos_idPré-requisitos`)
    REFERENCES `mydb`.`Pré-requisitos` (`idPré-requisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Professor_idProfessor` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  `Professor_Departamento_idDepartamento` INT NOT NULL,
  `Professor_Departamento_idDepartamento1` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_Pessoa_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Professor_idProfessor` ASC) VISIBLE,
  INDEX `fk_Pessoa_Professor1_idx` (`Professor_idProfessor` ASC, `Professor_Departamento_idDepartamento` ASC, `Professor_Departamento_idDepartamento1` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Professor_idProfessor`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Professor_idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Professor1`
    FOREIGN KEY (`Professor_idProfessor` , `Professor_Departamento_idDepartamento` , `Professor_Departamento_idDepartamento1`)
    REFERENCES `mydb`.`Professor` (`idProfessor` , `Departamento_idDepartamento` , `Departamento_idDepartamento1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Periodo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Periodo` (
  `idPeriodo` INT NOT NULL,
  `Ano` DATE NULL,
  `Semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta de Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oferta de Disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oferta de Disciplina` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Disciplina_Professor_idProfessor` INT NOT NULL,
  `Periodo_idPeriodo` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Disciplina_Professor_idProfessor`, `Periodo_idPeriodo`),
  INDEX `fk_Disciplina_has_Periodo_Periodo1_idx` (`Periodo_idPeriodo` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Periodo_Disciplina1_idx` (`Disciplina_idDisciplina` ASC, `Disciplina_Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Periodo_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina` , `Disciplina_Professor_idProfessor`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina` , `Professor_idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Periodo_Periodo1`
    FOREIGN KEY (`Periodo_idPeriodo`)
    REFERENCES `mydb`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno Matriculado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno Matriculado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno Matriculado` (
  `Aluno_idAluno` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Curso_idCurso`),
  INDEX `fk_Aluno_has_Curso_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Curso_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Curso_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Extensão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Extensão` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Extensão` (
  `idExtensão` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Instituição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExtensão`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matriculado Extensão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matriculado Extensão` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Matriculado Extensão` (
  `Extensão_idExtensão` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`Extensão_idExtensão`, `Aluno_idAluno`, `Aluno_Professor_idProfessor`),
  INDEX `fk_Extensão_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Professor_idProfessor` ASC) VISIBLE,
  INDEX `fk_Extensão_has_Aluno_Extensão1_idx` (`Extensão_idExtensão` ASC) VISIBLE,
  CONSTRAINT `fk_Extensão_has_Aluno_Extensão1`
    FOREIGN KEY (`Extensão_idExtensão`)
    REFERENCES `mydb`.`Extensão` (`idExtensão`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Extensão_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Professor_idProfessor`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Professor_idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` INT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `PNome` VARCHAR(45) NOT NULL,
  `Nmeio` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL COMMENT 'Adcionar contraint de unicidade para (nome completo) \nunique (Nome, M, Sobrenome)',
  `Identificação_documento` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `PJ_idCliente` INT NOT NULL,
  `PF_idCliente` INT NOT NULL,
  `Dt_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idCliente`, `Dt_nascimento`, `PF_idCliente`, `PJ_idCliente`),
  UNIQUE INDEX `Identificação_documento_UNIQUE` (`Identificação_documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `CNPJ` INT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  `Codigo_de_rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Tipo_Pagamento` VARCHAR(45) NOT NULL,
  `Vencimento` VARCHAR(45) NOT NULL,
  `Nome_cartão_1` VARCHAR(45) NOT NULL,
  `Numero_CArtão_1` VARCHAR(45) NOT NULL,
  `Nome_cartão_2` VARCHAR(45) NOT NULL,
  `Numero_cartão_2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Status` ENUM('EM ANDAMENTO', 'PROCESSANDO', 'ENVIADO', 'ENTREGUE') NOT NULL DEFAULT 'PROCESSANDO',
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Entrega_idEntrega`, `Pagamento_idPagamento`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  INDEX `fk_Pedido_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilizando um produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disponibilizando um produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilizando um produto` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação de Produto/pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Relação de Produto/pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Relação de Produto/pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  `Status` ENUM('DISPONIVEL', 'SEM ESTOQUE') NULL DEFAULT 'DISPONIVEL' COMMENT 'ENUM(\'DISPONIVEL\',\'SEM ESTOQUE\'\')',
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`, `Quantidade`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceiro - Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terceiro - Vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terceiro - Vendedor` (
  `idTerceiro - Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Nome Fantasia` VARCHAR(45) NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`),
  UNIQUE INDEX `Razão Social_UNIQUE` (`Razão Social` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos por vendedor (terceiros)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos por vendedor (terceiros)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos por vendedor (terceiros)` (
  `Terceiro - Vendedor_idTerceiro - Vendedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`, `Produto_idProduto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`Terceiro - Vendedor_idTerceiro - Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`)
    REFERENCES `mydb`.`Terceiro - Vendedor` (`idTerceiro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PF` (
  `idCliente` INT NOT NULL,
  `CPF` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Cliente_idCliente`),
  INDEX `fk_PF_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_PF_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos_Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamentos_Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos_Clientes` (
  `Pagamento_idPagamento` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Pagamento_idPagamento`, `Cliente_idCliente`),
  INDEX `fk_Pagamento_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pagamento_has_Cliente_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_has_Cliente_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF/CNPJ` INT NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `CLIENTEcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VEICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VEICULO` (
  `idVEICULO` INT NOT NULL,
  `PLACA` VARCHAR(45) NULL,
  `MODELO` VARCHAR(45) NULL,
  `ANO` INT NULL,
  `MARCA` VARCHAR(45) NULL,
  `COR` VARCHAR(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idVEICULO`, `CLIENTE_idCLIENTE`),
  INDEX `fk_VEICULO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MECANICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MECANICO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MECANICO` (
  `idMECANICO` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMECANICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDEM_SERVIÇO(OS)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDEM_SERVIÇO(OS)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDEM_SERVIÇO(OS)` (
  `idORDEM_SERVIÇO(OS)` INT NOT NULL,
  `Data_de_Emissão` DATE NULL,
  `Data_de_Conclusão` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Valor_Total` DECIMAL(11) NULL,
  `VEICULO_idVEICULO` INT NOT NULL,
  `VEICULO_CLIENTE_idCLIENTE` INT NOT NULL,
  `MECANICO_idMECANICO` INT NOT NULL,
  PRIMARY KEY (`idORDEM_SERVIÇO(OS)`, `VEICULO_idVEICULO`, `VEICULO_CLIENTE_idCLIENTE`, `MECANICO_idMECANICO`),
  INDEX `fk_ORDEM_SERVIÇO(OS)_VEICULO1_idx` (`VEICULO_idVEICULO` ASC, `VEICULO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVIÇO(OS)_MECANICO1_idx` (`MECANICO_idMECANICO` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEM_SERVIÇO(OS)_VEICULO1`
    FOREIGN KEY (`VEICULO_idVEICULO` , `VEICULO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`VEICULO` (`idVEICULO` , `CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVIÇO(OS)_MECANICO1`
    FOREIGN KEY (`MECANICO_idMECANICO`)
    REFERENCES `mydb`.`MECANICO` (`idMECANICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVIÇO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SERVIÇO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SERVIÇO` (
  `idSERVIÇO` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Valor_da_Mão_de_Obra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSERVIÇO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEÇA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PEÇA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PEÇA` (
  `idPEÇA` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor_Unitário` VARCHAR(45) NULL,
  PRIMARY KEY (`idPEÇA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDEM_SERVIÇO(OS) POSSUI SERVIÇOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDEM_SERVIÇO(OS) POSSUI SERVIÇOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDEM_SERVIÇO(OS) POSSUI SERVIÇOS` (
  `ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` INT NOT NULL,
  `SERVIÇO_idSERVIÇO` INT NOT NULL,
  PRIMARY KEY (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)`, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO`, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`, `SERVIÇO_idSERVIÇO`),
  INDEX `fk_ORDEM_SERVIÇO(OS)_has_SERVIÇO_SERVIÇO1_idx` (`SERVIÇO_idSERVIÇO` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVIÇO(OS)_has_SERVIÇO_ORDEM_SERVIÇO(OS)1_idx` (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEM_SERVIÇO(OS)_has_SERVIÇO_ORDEM_SERVIÇO(OS)1`
    FOREIGN KEY (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` , `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` , `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`ORDEM_SERVIÇO(OS)` (`idORDEM_SERVIÇO(OS)` , `VEICULO_idVEICULO` , `VEICULO_CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVIÇO(OS)_has_SERVIÇO_SERVIÇO1`
    FOREIGN KEY (`SERVIÇO_idSERVIÇO`)
    REFERENCES `mydb`.`SERVIÇO` (`idSERVIÇO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDEM_SERVIÇO(OS) USA PEÇAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDEM_SERVIÇO(OS) USA PEÇAS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDEM_SERVIÇO(OS) USA PEÇAS` (
  `PEÇA_idPEÇA` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`PEÇA_idPEÇA`, `ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)`, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO`, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`),
  INDEX `fk_PEÇA_has_ORDEM_SERVIÇO(OS)_ORDEM_SERVIÇO(OS)1_idx` (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_PEÇA_has_ORDEM_SERVIÇO(OS)_PEÇA1_idx` (`PEÇA_idPEÇA` ASC) VISIBLE,
  CONSTRAINT `fk_PEÇA_has_ORDEM_SERVIÇO(OS)_PEÇA1`
    FOREIGN KEY (`PEÇA_idPEÇA`)
    REFERENCES `mydb`.`PEÇA` (`idPEÇA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEÇA_has_ORDEM_SERVIÇO(OS)_ORDEM_SERVIÇO(OS)1`
    FOREIGN KEY (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` , `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` , `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`ORDEM_SERVIÇO(OS)` (`idORDEM_SERVIÇO(OS)` , `VEICULO_idVEICULO` , `VEICULO_CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MECANICO EXECUTA ORDEM_SERVIÇO(OS)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MECANICO EXECUTA ORDEM_SERVIÇO(OS)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MECANICO EXECUTA ORDEM_SERVIÇO(OS)` (
  `MECANICO_idMECANICO` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` INT NOT NULL,
  `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`MECANICO_idMECANICO`, `ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)`, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO`, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`),
  INDEX `fk_MECANICO_has_ORDEM_SERVIÇO(OS)_ORDEM_SERVIÇO(OS)1_idx` (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` ASC, `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_MECANICO_has_ORDEM_SERVIÇO(OS)_MECANICO1_idx` (`MECANICO_idMECANICO` ASC) VISIBLE,
  CONSTRAINT `fk_MECANICO_has_ORDEM_SERVIÇO(OS)_MECANICO1`
    FOREIGN KEY (`MECANICO_idMECANICO`)
    REFERENCES `mydb`.`MECANICO` (`idMECANICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MECANICO_has_ORDEM_SERVIÇO(OS)_ORDEM_SERVIÇO(OS)1`
    FOREIGN KEY (`ORDEM_SERVIÇO(OS)_idORDEM_SERVIÇO(OS)` , `ORDEM_SERVIÇO(OS)_VEICULO_idVEICULO` , `ORDEM_SERVIÇO(OS)_VEICULO_CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`ORDEM_SERVIÇO(OS)` (`idORDEM_SERVIÇO(OS)` , `VEICULO_idVEICULO` , `VEICULO_CLIENTE_idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PJ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PJ` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PJ` (
  `idCliente` INT NOT NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Cliente_idCliente`),
  INDEX `fk_PJ_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_PJ_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
